### ISSUE TITLE
Appcompat-v7:25.4.0 does not exist

### ISSUE THREAD

**Issue by MotassemJa** [adorsys/secure-storage-android#11]
In your gradle you are using version 25.4.0 which does not exist according to [https://developer.android.com/topic/libraries/support-library/packages.html](the docs).

When trying to add the latest release, I'm getting "Failed to resolve" error and not being able to install the repoisitory and sync project.

**Comment by luckyhandler** [comment]
thanks for reporting. We will look into the issue and solve it with our next version

**Comment by luckyhandler** [comment]
If you look at https://developer.android.com/topic/libraries/support-library/revisions.html#25-4-0 you will see that the version exists but we might have an issue with the new google repository. For a quick fix you should follow these steps to make it work again:
https://developer.android.com/topic/libraries/support-library/setup.html

**Comment by MotassemJa** [comment]
Thank you!
