### ISSUE TITLE
SecureStorageException doesn't exist

### ISSUE THREAD

**Issue by Ornolfr** [adorsys/secure-storage-android#15]
In README.md you explain error handling with this class. But it cannot be resolved. The version I'm using is:
`'de.adorsys.android:securestoragelibrary:0.0.3'`

**Comment by drilonrecica** [comment]
We are working on fixing the issue.
We'll keep you informed @Ornolfr

**Comment by drilonrecica** [comment]
Sorry for the inconvenience.
We have fixed the issue and also made some minor changes to library usage.
Please use version 1.0.0
`compile 'de.adorsys.android:securestoragelibrary:1.0.0'`
One of the changes is that you no longer need to pass the context as a parameter, cause that is all handled internally.
@Ornolfr
