### ISSUE TITLE
Remove minSdk from manifest

### ISSUE THREAD

**Issue by Kranuh** [adorsys/secure-storage-android#22]
I know that this library isn't compatible with anything < API 18, but you should allow developers to implement regardless of their api level. Right now on a project that has minSdk set to 16 we'll be forced to use tools:replace in our manifest. Why not do runtime checks on the api level instead of forcing it trough the manifest?

Thanks for the library though! Incredibly useful.

**Comment by luckyhandler** [comment]
Hi Kranuh,
for providing the users of the library the latest security we use the KeyStore and the KeyPairGenerator which was introduced in API 18. It ensures that the keys are stored in a secure part of your processor - in your hardware so to say which is unreachable for anyone. 
We do not provide a software keystore as we don't trust in its security. So it doesn't make sense to use this library in any application that targets a lower api.

Check out https://developer.android.com/training/articles/keystore.html#UsingAndroidKeyStore for more details... Thanks for the report though.
