### ISSUE TITLE
Manifest merger error

### ISSUE THREAD

**Issue by gligorkot** [adorsys/secure-storage-android#23]
Hi all,

Thanks for providing such an easy to use library.

Please note as I added your library I got this error when trying to build my app:

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:10:9-35
is also present at [de.adorsys.android:securestoragelibrary:1.0.0] AndroidManifest.xml:11:9-36 value=(false).
Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:8:5-31:19 to override.
```

The workaround is to add what is suggested in the error above, however according to this article [https://android.jlelse.eu/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a](url) it is probably a good idea to remove the 2 lines from the library so that this doesn't happen to new users of the lib.

Cheers and thanks again!

G

**Comment by drilonrecica** [comment]
Hi @gligorkot 

We will be looking into this. We'll keep you informed for any possible changes to the library.

Cheers

D

**Comment by drilonrecica** [comment]
Hi @gligorkot ,

We have reviewed your request and decided to implement it in the library. 

It is currently in this PR https://github.com/adorsys/secure-storage-android/pull/25

It will be merged and released in the coming days.

Thank you for your support and input.

**Comment by gligorkot** [comment]
Excellent! Thanks.

**Comment by luckyhandler** [comment]
PR #25 has been merged into develop
