### ISSUE TITLE
TEE Statistics Claims

### ISSUE THREAD

**Issue by patrickfav** [adorsys/secure-storage-android#24]
You write

> Already 80–90% of all modern Android phones out there are equipped with a TEE (mostly because it’s often used to play DRM protected material) and it even is a requirement for Google’s Android Nougat certification — so every new phone running Android Nougat will come with a TEE installed.

I'm looking for statistics on this myself, from where are those number?

**Comment by drilonrecica** [comment]
Hi, 

We got the statistics from this medium post where there are infos about the keystore usage and benefits:
https://medium.com/overmorrow/authentication-sucks-bad-security-too-345ed20463d4
