### ISSUE TITLE
What is `defValue`?

### ISSUE THREAD

**Issue by spookyuser** [adorsys/secure-storage-android#26]
When trying to retrieve a `String` with `SecurePreferences.getStringValue("KEY")` an error is thrown because `defValue` is not provided. Is this supposed to be an optional parameter, because it isn't listed in the readme.

**Comment by drilonrecica** [comment]
Hi @spookyUnknownUser 

We will look into this ASAP.

We'll keep you posted.

**Comment by luckyhandler** [comment]
@spookyUnknownUser, I created a pull request with an update to the readme. The def value is necessary as it gives you the full control over what to get back from the library if the value is not in the storage. As soon as #27 is merged I will close this issue. Hopefully, this helps you!

**Comment by luckyhandler** [comment]
#27 merged into master

**Comment by spookyuser** [comment]
Perfect thank you.
