### ISSUE TITLE
Can't decrypt after app uninstall/re-install

### ISSUE THREAD

**Issue by joey-harward** [adorsys/secure-storage-android#32]
I am using Auto Backup to save my shared preferences including the encrypted values in SecurePreferences.xml.  However, I have noticed that after an uninstall/re-install that the values in SecurePreferences can't be decrypted.  The specific error is "KeyPair does not exist in Keystore".

So do key pairs in the Keystore survive app installs?  If so, how can I achieve this?

**Comment by luckyhandler** [comment]
Hi @joey-harward, this cannot work as every device has its own private key which is used for encryption and decryption. You are not able to decrypt data which was encrypted on another device. That's what makes this library and it's encrypting secure.

**Comment by joey-harward** [comment]
This is happening when uninstalling then reinstalling on the SAME device.  Is the private key of a device different after uninstalling?

**Comment by luckyhandler** [comment]
the key is also different on reinstall as it gets deleted when uninstalling an app which uses SecureStorage. When the app starts for the first time another key pair is generated and then decryption fails as it was encrypted with another key.

**Comment by joey-harward** [comment]
That's what I was afraid of.  I need secure data that survives installs.  Thanks for your help.
