### ISSUE TITLE
KeyPairGeneratorSpec deprecated

### ISSUE THREAD

**Issue by joey-harward** [adorsys/secure-storage-android#36]
It looks like Google has deprecated _KeyPairGeneratorSpec_ in favor of **KeyGenParameterSpec**.

**Comment by drilonrecica** [comment]
We are currently developing [SecureStorage2](https://github.com/adorsys/secure-storage2-android) which will contain solutions to all issues in SecureStorage like this, maximum String length etc.
We thank you for your input and we'll keep you posted about SecureStorage2

**Comment by joey-harward** [comment]
Awesome! Thank you so much for your efforts.
