### ISSUE TITLE
NullPointerException: Securestoragelibrary.SecurePreferences.contains

### ISSUE THREAD

**Issue by NathanSass** [adorsys/secure-storage-android#37]
Hello,
I'm having a crash. When the app is backgrounded for periods of time, the system kills it. When the app re-initializes and dagger is setup again, I get this crash.

```java
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at de.adorsys.android.securestoragelibrary.SecurePreferences.contains(Unknown Source:2)
```

Any ideas?

**Comment by luckyhandler** [comment]
Hey, thanks for reporting this. So you use SecureStorage with Dagger? Why? You can access every method statically. No additional setup required.

**Comment by NathanSass** [comment]
I'm not injecting `SecurePreferences` with dagger. I'm injecting my own implementation that uses your lib & references it statically.

```java
internal interface SecureStorage {
    val downloadSecretKey: ByteArray
}

internal class SecureStorageImpl : SecureStorage {
    private companion object {
        const val DOWNLOAD_KEY = "download_key"
        const val STRING_LENGTH = 20
        const val ALLOWED_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz0123456789"
    }

    override val downloadSecretKey: ByteArray
        get() {
            return if (SecurePreferences.contains(DOWNLOAD_KEY)) {
                SecurePreferences.getStringValue(DOWNLOAD_KEY, null)!!.toSecretByteArray
            } else {
                randomString.apply {
                    SecurePreferences.setValue(DOWNLOAD_KEY, this)
                }.toSecretByteArray
            }

        }

    private val randomString: String
        get() {
            return (1..STRING_LENGTH)
                    .map { ALLOWED_CHARS.random() }
                    .joinToString("")
        }

    private val String.toSecretByteArray: ByteArray
        get() {
            val keyBytes = ByteArray(16)
            val md = MessageDigest.getInstance("SHA-256")
            md.update(this.toByteArray())
            System.arraycopy(md.digest(), 0, keyBytes, 0, keyBytes.size)
            return keyBytes
        }
}
```

The line with `SecurePreferences.contains(DOWNLOAD_KEY)` is crashing

More specific reproduction steps:
1. Close the app
2. Click on the leak canary app to check for leaks.
3. This crash occurs.

I think it has something to do with how SecureStorageLibrary is retaining context.

**Comment by luckyhandler** [comment]
We will look into the issue. It's related to the apps context. We use a ContentProvider to get the Context, which doesn't work in your case...

**Comment by luckyhandler** [comment]
Hi @NathanSass, we refactored the way we handle context in SecureStorage. This implies you now have to pass the context directly to the methods. This solves your problem. Make sure to update to 1.1.0 as soon as possible

**Comment by luckyhandler** [comment]
1.1.0 has just been released
