### ISSUE TITLE
Questions: Where are the data stored?

### ISSUE THREAD

**Issue by MotassemJa** [adorsys/secure-storage-android#6]
Could you please explain to me where exactly are the data being saved? In SharedPreferences or in the KeyStore?

**Comment by drilonrecica** [comment]
@MotassemJa  
The KeyStore can only be used for Storing Encryption keys.
The data is stored in the SharedPreferences but in an encrypted form while the keys for en/decryption are stored in the Android KeyStore.

**Comment by drilonrecica** [comment]
I'm closing this issue as the question has been answered in detail.
