### ISSUE TITLE
implementation "de.adorsys.android:securestoragelibrary:${latestSecureStorageVersion}"

### ISSUE THREAD

**Issue by KashifJavaid** [adorsys/secure-storage-android#63]
Hi, 

Sorry if I am asking at wrong . But I am unable to install your library , First , it could not find the latestSecureStorageVersion variable , then I removed it and later it could not resolve de.adorsys.android:securestoragelibrary.

Is there some help you can provide , or point me in right direction in terms of using your library? 

Many Thanks

**Comment by KashifJavaid** [comment]
> Hi,
> 
> Sorry if I am asking at wrong . But I am unable to install your library , First , it could not find the latestSecureStorageVersion variable , then I removed it and later it could not resolve de.adorsys.android:securestoragelibrary.
> 
> Is there some help you can provide , or point me in right direction in terms of using your library?
> 
> Many Thanks

I was able to install using version 1.2.2 my bad I could not figure out right version .

**Comment by luckyhandler** [comment]
ok perfect!
