### ISSUE TITLE
Input size limit of 256 bytes

### ISSUE THREAD

**Issue by FilipeMLFreitas** [adorsys/secure-storage-android#82]
Hello guys,

I really like your library and was hoping to use in a new project for added security but I ran into the input size limit of 256 bytes when saving a value.
I need to store OpenId tokens and I've read that I need some 1024 bytes so the 256 bytes limit really makes it impossible.
In the future, would there be a solution to be able to store bigger strings?
Thanks!

**Comment by drilonrecica** [comment]
Hi @FilipeMLFreitas ,

That is a shortcoming of the RSA encryption protocol that is used in SecureStorage.
You can take a look at this https://github.com/adorsys/secure-storage-android/issues/28#issuecomment-424394160 as a workaround for what you are trying to achieve.

I am also now in the final stages of developing SecureStorage 2.0 which handles the whole encryption process differently and doesn't have the shortcomings of its predecessor.
So with SecureStorage 2.0 you would have no problem storing long strings, tokens etc.
I am hoping that I can finish and release version 2.0 in the next few weeks so maybe that is something that can be of benefit for you.
SecureStorage2 logic is currently in the develop branch.

Thank you for using SecureStorage

**Comment by triplef** [comment]
@drilonrecica do you have any update on the SecureStorage 2.0 release that fixes the size limit? Thanks!

**Comment by drilonrecica** [comment]
I will finish the development and deployment of SecureStorage2 on [my fork of SecureStorage](https://github.com/drilonrecica/secure-storage-android) (at least temporarily). Watch and star that repository to be informed about it.
