### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by hatpick** [adorsys/secure-storage-android#9]
Why minSdkVersion is set to 14? Shouldn't it be 18, all the calls require it 18+.

**Comment by drilonrecica** [comment]
We will look into this, and inform you ASAP @hatpick

**Comment by drilonrecica** [comment]
@hatpick 
We are setting minSdkVersion to 18.
We will inform you as soon as it is merged to master branch.

**Comment by luckyhandler** [comment]
has been merged to develop
