### ISSUE TITLE
last version

### ISSUE THREAD

**Issue by ayoubAnbara** [adorsys/secure-storage-android#98]
what is the last version of this library?

**Comment by aqoong** [comment]
maybe 0.0.2

I searched it on Jitpack.io.

**Comment by aqoong** [comment]
> what is the last version of this library?

maybe 0.0.2

I searched it on Jitpack.io.

**Comment by ayoubAnbara** [comment]
I think 1.2.4 
`implementation "de.adorsys.android:securestoragelibrary:1.2.4"`

**Comment by TonyLead** [comment]
where is you find 1.2.4 ?
